### ISSUE TITLE
Inconsistent use of lower case in snake object method names

### ISSUE THREAD

**Issue by Northern-Web** [Northern-Web/Sanke#13]
Some of the snake object methods which returns a boolean value, is named with a capital first letter, while some are not. This proves to be inconsistent coding of method names. It violates coding conventions and makes readability harder. See example below:

- `isOutOfBounds()`
- `IsTouchingItself()`
- `IsMovementKey()`

**Suggested change:**
Refactor function names to all use capital first letters.

**Comment by lassag** [comment]
Fixed in 9f5beb16c758fb6c42203c305520e4a86c3ea399
