### ISSUE TITLE
Food sometimes get generated within the snake

### ISSUE THREAD

**Issue by Northern-Web** [Northern-Web/Sanke#14]
**Describe the bug**
The food occationally gets generated and rendered on the snakes head or tail.

**To Reproduce**
1. Launch current running version of Sanke
2. Play some rounds in order to see different food generations.
3. Observe that the food sometimes generates within the snake.

**Expected behavior**
The food should not be allowed to generate within the snake.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 79.0.3945.88

**Comment by lassag** [comment]
Fixed in #16 667a35770597fbf2d596cb7d2791c230e0be3ac5
