### ISSUE TITLE
Snake field of view

### ISSUE THREAD

**Issue by Northern-Web** [Northern-Web/Sanke#19]
**Describe the solution you'd like**
I would like to provide the snake with a field of view. Directions left, right and front of the head, relative to its position. The field of view need to accept X amount of blocks in each of the directions.

The snake is supposed to make decisions based on the FoV.

**Additional context**
![Snake Field of View](https://user-images.githubusercontent.com/37421966/71632382-9047a480-2c0e-11ea-9e8f-04647fd1ed3c.png)

_Black = Snake tail_
_Blue = Snake head_
_Green = Field of view_

**Comment by lassag** [comment]
Fixed in Pull Request #24
